datasource:
  db:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}

ebean:
  docstore:
    url: http://${ELASTIC_HOST}:${ELASTIC_PORT}
    active: true
    generateMapping: true
    dropCreate: false
  migration:
    run: true
